version: "3.7"

services:

  ktor-singleton-cio:
    build:
      dockerfile: Dockerfile
      context: ./ktorSingletonCio/
    ports:
      - "8080:8080"
    environment:
      - REMOTE_CLIENT_URL=http://nginx:80
    depends_on:
      - nginx

  locust:
    environment:
      - TARGET_URL=http://ktor-singleton-cio:8080
    depends_on:
      - ktor-singleton-cio
