version: "3.7"

services:

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    ports:
      - "8181:80"

  locust:
    build:
      dockerfile: Dockerfile
      context: ./locust/
    ports:
      - "5557:5557"
      - "5558:5558"
      - "8089:8089"
