version: "3.7"

services:

  ktor-call-cio:
    build:
      dockerfile: Dockerfile
      context: ./ktorCallCio/
    ports:
      - "8080:8080"
    environment:
      - REMOTE_CLIENT_URL=http://nginx:80
    depends_on:
      - nginx

  locust:
    environment:
      - TARGET_URL=http://ktor-call-cio:8080
    depends_on:
      - ktor-call-cio
